version: 0.2

env:
  variables:
    S3_BUCKET: "awsapplication"
    APP_NAME: "Applicationform"
    BUILD_ENV: "QA"
   

phases:
  install:
    runtime-versions:
      # NodeJS included in the docker image
      nodejs: 12
    commands:
      # Install node dependancies.
      - npm install

build:
    commands:
      # Builds Angular application.
      - node ./node_modules/@angular/cli/bin/ng build --$BUILD_ENV

post_build:
    commands:
      -aws s3 sync ./dist/$APP_NAME s3://$S3_BUCKET --acl 'public-read' --delete
      
      


          